# Generated by Django 5.1.7 on 2025-03-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_and_item_models_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('в процессе', 'В процессе'), ('завершен', 'Завершен')], default='В ожидании', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
