# Generated by Django 5.1.7 on 2025-03-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_model_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('готов', 'Готов'), ('оплачен', 'Оплачен')], max_length=100),
        ),
    ]
